apiVersion: v1
kind: Service
metadata:
  name: apache-server
  namespace: autoscale
spec:
  selector:
    app: apache-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
