apiVersion: v1
kind: Pod
metadata:
  name: crash-pod
spec:
  priorityClassName: high-priority-lab
  containers:
  - name: busybox
    # Intentionally invalid image tag to cause ImagePullBackOff
    image: busybox:nonexistent
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "300m"
        memory: "128Mi"