apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: nginx-static
spec:
  type: ClusterIP
  selector:
    app: nginx-static
  ports:
    - name: https
      port: 443
      targetPort: 443
