apiVersion: v1
kind: Pod
metadata:
  name: toleration-test
spec:
  priorityClassName: high-priority-lab
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "200m"
        memory: "64Mi"