apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod
spec:
  # This pod references a PriorityClass that may not exist yet.
  priorityClassName: high-priority-lab
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"