apiVersion: v1
kind: Pod
metadata:
  name: nonpreempting-pod
spec:
  priorityClassName: high-priority-nonpreempting
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "400m"
        memory: "64Mi"