apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
spec:
  priorityClassName: high-priority-lab
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - production
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        cpu: "400m"
        memory: "128Mi"