apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: storageclass-lab
spec:
  # Leave storageClassName unset so Kubernetes uses the default storage class.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi